version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  redis:
    image: redis:3.2

  nginx:
    build:
      context: ./.docker/services/
      dockerfile: ./nginx/build/Dockerfile
    command: [/bin/bash, .docker/services/nginx/build/command.sh]
    ports:
      - "443:443"
      - "6969:6969"
    volumes:
      - ./.docker/services/nginx/conf:/etc/nginx/conf.d
      - .:/var/www/app
    working_dir: /var/www/app

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=Minhkhoi93!@#
    ports:
      - '13306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  nodejs:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db:
    driver: local